M48
; DRILL file {KiCad 9.0.5} date 2025-10-08T11:58:02+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-08T11:58:02+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.702
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.429
%
G90
G05
T1
X99.78Y-69.2
T2
X99.5Y-65.0
X110.5Y-65.0
T3
X105.0Y-59.05
X110.0Y-61.25
T4
X105.0Y-65.0
M30
